{-# OPTIONS --safe #-}

-- Local imports: Architectures
open import Arch.General.Execution using (Execution; WellFormed)
open import Arch.LIMM using (LabelLIMM)
-- Local imports: Theorem Specification
open import TransformFRAW using (FRAW-Restricted)


-- | "Read-after-Write with Fence" elimination proof
module Proof.Elimination.FRAW
  -- Given a target execution
  (dst : Execution LabelLIMM)
  -- which is generated by a program produced through the mapping
  (dst-ok : FRAW-Restricted dst)
  where

-- Stdlib imports
open import Data.Product using (_×_; _,_; ∃-syntax)
-- Local imports: Architectures
open import Arch.General.Execution
open import Arch.LIMM
-- Local imports: Relations
open import Dodo.Binary
-- Local imports: Proofs
open import TransformFRAW using (FRAWMapping)
open import Proof.Elimination.FRAW.Execution dst dst-ok
open import Proof.Elimination.FRAW.WellFormed dst dst-ok
open import Proof.Elimination.FRAW.Consistent dst dst-ok
open import Proof.Elimination.FRAW.Mapping dst dst-ok
open import Proof.Elimination.FRAW.Behavior dst dst-ok
import Proof.Elimination.Framework dst dst-wf as Δ


open Δ.Definitions δ
open Arch.General.Execution


proof-FRAW :
  -- We produce a source execution
  ∃[ src ]
    ( -- which is wellformed,
      WellFormed src
    × -- consistent in the source architecture,
      IsLIMMConsistent src
    × -- related to the target by the mapping on instructions,
      FRAWMapping src dst-ok
    × -- and has identical behavior to the target
      behavior src ⇔₂ behavior dst
    )
proof-FRAW =
  ( src
  , src-wf
  , src-consistent
  , src-mapping
  , src-behavior
  )
